
name: PublishAddon

on:
  push:
    branches:
      - main
      - 'DI-20860---Notifications-device-UI-populated-after-a-long-time---iOS'

jobs:
  publish-addon:
    uses:  Pepperi-Addons/development-guidelines/.github/workflows/publish.yml@master
    secrets:
      PEPPERI_ADDON_PUBLISH_KEY: ${{ secrets.PEPPERI_ADDON_PUBLISH_KEY }}